spring:
  application:
    name: 'client2'
server:
  port: 8080
eureka:
  instance:
    hostname: ${vcap.application.uris[0]:localhost}
    prefer-ip-address: true
    lease-renewal-interval-in-seconds: 10
  client:
    service-url:
      defaultzone : http://localhost:9090/eureka

